"""fairness.rotate_user_seed — commit-reveal seed lifecycle.

Revision ID: 0025_fairness_rotate_user_seed
Revises: 0024_luck_helpers
Create Date: 2026-05-04

Closes Story 2.8d and Epic 2 of the Luck plan.

The fn that bootstraps a user's provably-fair state on first
play AND rotates it on demand thereafter. Implements the spec
§4.2 lifecycle:

    First time the user plays:
      generate server_seed (CSPRNG)
      store (server_seed, sha256(server_seed),
             client_seed=random_hex(16), nonce=0)

    User runs /rotateseed:
      insert old (server_seed, hash, client_seed, last_nonce,
                  started_at) into fairness.history
      generate new server_seed
      reset nonce=0
      preserve client_seed (only /setseed changes it)

## Signature

    fairness.rotate_user_seed(
        p_discord_id BIGINT,
        p_rotated_by TEXT  -- 'user' | 'system' | 'admin'
    )
    RETURNS TABLE (
        revealed_server_seed  BYTEA,   -- the OLD seed, now public
        new_server_seed_hash  BYTEA    -- the NEW commitment
    )

On first rotation, ``revealed_server_seed`` is NULL because there
is no prior seed to reveal.

## Implementation

- ``server_seed`` = 32 random bytes from ``public.gen_random_bytes(32)``
  (pgcrypto, enabled by migration 0002 for the audit chain).
- ``server_seed_hash`` = ``public.digest(server_seed, 'sha256')``
  (32 bytes).
- ``client_seed`` on bootstrap defaults to a 16-char hex string
  generated by ``encode(public.gen_random_bytes(8), 'hex')``.
- The history insert writes ``rotated_by`` directly; the existing
  CHECK on ``fairness.history.rotated_by`` raises on invalid values.
  The SDF re-raises with a clearer ``invalid_rotated_by`` name.

## Privilege

REVOKE ALL FROM PUBLIC; GRANT EXECUTE TO deathroll_luck and
deathroll_dw. Spec §3.1 pre-positions D/W to be able to bind seed
rotation to the withdraw cycle in v1.x. deathroll_readonly cannot
EXECUTE.
"""

from alembic import op

revision = "0025_fairness_rotate_user_seed"
down_revision = "0024_luck_helpers"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    CREATE OR REPLACE FUNCTION fairness.rotate_user_seed(
        p_discord_id BIGINT,
        p_rotated_by TEXT
    )
    RETURNS TABLE (
        revealed_server_seed  BYTEA,
        new_server_seed_hash  BYTEA
    )
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path = fairness, core, pg_catalog AS $$
    DECLARE
        v_existing       fairness.user_seeds%ROWTYPE;
        v_new_seed       BYTEA;
        v_new_hash       BYTEA;
        v_new_client     TEXT;
    BEGIN
        IF p_rotated_by NOT IN ('user', 'system', 'admin') THEN
            RAISE EXCEPTION 'invalid_rotated_by: %', p_rotated_by;
        END IF;

        -- Lock the existing row if present (NO-OP if not, with FOR UPDATE).
        SELECT * INTO v_existing
        FROM fairness.user_seeds
        WHERE discord_id = p_discord_id
        FOR UPDATE;

        -- Generate fresh seed material via pgcrypto. The functions
        -- are in the public schema; the SECURITY DEFINER search_path
        -- is locked to (fairness, core, pg_catalog), so we
        -- fully-qualify.
        v_new_seed   := public.gen_random_bytes(32);
        v_new_hash   := public.digest(v_new_seed, 'sha256');

        IF NOT FOUND THEN
            -- First-time provisioning: no prior to archive. Generate
            -- the default client_seed (16-char hex from 8 random bytes).
            v_new_client := encode(public.gen_random_bytes(8), 'hex');

            INSERT INTO fairness.user_seeds (
                discord_id, server_seed, server_seed_hash, client_seed,
                nonce, created_at, rotated_at
            ) VALUES (
                p_discord_id, v_new_seed, v_new_hash, v_new_client,
                0, NOW(), NOW()
            );

            revealed_server_seed := NULL;
            new_server_seed_hash := v_new_hash;
            RETURN NEXT;
            RETURN;
        END IF;

        -- Existing row: archive the current state into history.
        -- Append-only triggers on history accept INSERT.
        INSERT INTO fairness.history (
            discord_id, revealed_server_seed, server_seed_hash,
            client_seed, last_nonce, started_at, rotated_at, rotated_by
        ) VALUES (
            p_discord_id,
            v_existing.server_seed,
            v_existing.server_seed_hash,
            v_existing.client_seed,
            v_existing.nonce,
            v_existing.rotated_at,
            NOW(),
            p_rotated_by
        );

        -- Update the live row with new seed material; reset nonce;
        -- preserve client_seed.
        UPDATE fairness.user_seeds SET
            server_seed       = v_new_seed,
            server_seed_hash  = v_new_hash,
            nonce             = 0,
            rotated_at        = NOW()
        WHERE discord_id = p_discord_id;

        revealed_server_seed := v_existing.server_seed;
        new_server_seed_hash := v_new_hash;
        RETURN NEXT;
        RETURN;
    END;
    $$;

    REVOKE ALL ON FUNCTION fairness.rotate_user_seed(BIGINT, TEXT)
        FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION fairness.rotate_user_seed(BIGINT, TEXT)
        TO deathroll_luck, deathroll_dw;
    """)


def downgrade() -> None:
    op.execute("""
        DROP FUNCTION IF EXISTS fairness.rotate_user_seed(BIGINT, TEXT);
    """)
